blank_issus_enabled: true
contact_links:
  - name: test
    url: https://github.com/HwangJieun03/issue_test
    about: test
  - name: test
    url: https://github.com/HwangJieun03/issue_test
    about: test
